---
# tasks file for install_apache
- name: Install httpd service
  yum:
    name: httpd
    state: latest
  notify:
    - Start httpd service
    

- name: Copy index.html file to remote node
  copy:
    src: index.html
    dest: /var/www/html/index.html
  notify:
    - Restart httpd service
     
- name: Cofiguring firewall
  firewalld:
    service: http
    zone: public
    immediate: yes
    state: enabled
    permanent: true
